# Generated by Django 6.0.3 on 2026-03-16 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_active',
        ),
        migrations.AddField(
            model_name='person',
            name='contract_type',
            field=models.CharField(choices=[('actif', 'Actif'), ('contractuel', 'Contractuel')], default='actif', max_length=20),
        ),
        migrations.CreateModel(
            name='UniteQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.PositiveIntegerField()),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unite_quotas', to='server.unite')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unite_quotas', to='server.year')),
            ],
            options={
                'ordering': ['year', 'unite'],
                'unique_together': {('year', 'unite')},
            },
        ),
    ]
