# Generated by Django 6.0.3 on 2026-03-19 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_person_is_active_person_contract_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gains', to='server.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gains', to='server.person')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gains', to='server.unite')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gains', to='server.year')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losses', to='server.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losses', to='server.person')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losses', to='server.unite')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losses', to='server.year')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
