# Generated by Django 6.0.3 on 2026-03-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_gain_loss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='hire_date',
        ),
        migrations.AddField(
            model_name='job',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='server.grade'),
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='server.company'),
        ),
        migrations.AddField(
            model_name='person',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='server.job'),
        ),
        migrations.AddField(
            model_name='person',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='server.unite'),
        ),
    ]
