# Generated by Django 6.0.3 on 2026-04-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_assignment_options_alter_unitequota_options_and_more'),
        ('server', '0013_allow_null_year_on_assignment_gain_loss'),
    ]

    operations = [
    ]
