# Generated by Django 6.0.3 on 2026-03-27 08:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_allow_null_year_on_assignment_gain_loss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-year', 'job']},
        ),
        migrations.AlterModelOptions(
            name='unitequota',
            options={'ordering': ['-year', 'unite__name']},
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='server_assi_job_id_ff9afd_idx',
        ),
        migrations.RemoveField(
            model_name='job',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='person',
            name='company',
        ),
        migrations.RemoveField(
            model_name='person',
            name='job',
        ),
        migrations.RemoveField(
            model_name='person',
            name='unite',
        ),
        migrations.AddField(
            model_name='job',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.grade'),
        ),
        migrations.AddField(
            model_name='unitequota',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='server.unite'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='server.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='max_workers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='from_unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='server.unite'),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='to_unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='server.unite'),
        ),
        migrations.AlterField(
            model_name='unitequota',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='server.unite'),
        ),
    ]
