# Generated by Django 6.0.3 on 2026-04-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_alter_assignment_options_alter_unitequota_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unitequota',
            options={'ordering': ['year', 'unite']},
        ),
        migrations.RemoveField(
            model_name='job',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='unitequota',
            name='created_at',
        ),
        migrations.AddField(
            model_name='job',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='server.grade'),
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='server.company'),
        ),
        migrations.AddField(
            model_name='person',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='server.job'),
        ),
        migrations.AddField(
            model_name='person',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='server.unite'),
        ),
        migrations.AlterField(
            model_name='company',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='server.unite'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='server.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='max_workers',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='from_unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='server.unite'),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='to_unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='server.unite'),
        ),
        migrations.AlterField(
            model_name='unitequota',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unite_quotas', to='server.unite'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['job', 'year'], name='server_assi_job_id_ff9afd_idx'),
        ),
    ]
