# Generated by Django 6.0.3 on 2026-04-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_drop_zombie_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_in_quota',
            field=models.BooleanField(default=True),
        ),
    ]
