# Generated by Django 6.0.3 on 2026-04-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_job_is_in_quota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-rating', 'name']},
        ),
        migrations.AddField(
            model_name='grade',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
